export const INVOICES = {
    DATA_REQUESTED:'INVOICES_DATA_REQUESTED',
    DATA_FAILED:'INVOICES_DATA_FAILED',
    DATA_SUCCEEDED:'INVOICES_DATA_SUCCEEDED',
}

export const INVOICE = {
    DATA_REQUESTED:'INVOICE_DATA_REQUESTED',
    DATA_FAILED:'INVOICE_DATA_FAILED',
    DATA_SUCCEEDED:'INVOICE_DATA_SUCCEEDED',
}
